apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-es-ilm-policy-config
data:
  es_ilm_policy.json: |
    {
      "policy": {
        "phases": {
          "hot": {
            "min_age": "{{ .Values.esIlmPolicy.hotPhaseMinAge }}",
            "actions": {
              "set_priority": {
                "priority": {{ .Values.esIlmPolicy.hotPhasePriority }}
              }
            }
          },
          "cold": {
            "min_age": "{{ .Values.esIlmPolicy.coldPhaseMinAge }}",
            "actions": {
              "set_priority": {
                "priority": {{ .Values.esIlmPolicy.coldPhasePriority }}
              }
            }
          },
          "delete": {
            "min_age": "{{ .Values.esIlmPolicy.deletePhaseMinAge }}",
            "actions": {
              "delete": {}
            }
          }
        }
      }
    }
